// Build-time generator for src/assets/templates/chords.json.
//
// The C and Am templates are STATIC canonical hand configurations expressed
// in the same normalized coordinate space produced by src/cv/normalizer.ts.
// Templates are generated here (from the exact normalization code used at
// runtime) so the JSON stays perfectly in-sync. Templates are NOT generated
// by Gemini.
//
// Run: npm run generate:templates

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { normalizeHandLandmarks } from "../src/cv/normalizer";
import { buildRawAm, buildRawC } from "../src/assets/templates/canonicalHands";

const __dirname = dirname(fileURLToPath(import.meta.url));

const cNorm = normalizeHandLandmarks(buildRawC());
const amNorm = normalizeHandLandmarks(buildRawAm());

if (!cNorm.ok || !amNorm.ok) {
  throw new Error("Template normalization failed — check canonical geometry.");
}

const payload = {
  meta: {
    name: "StringsAttached ukulele chord templates",
    space:
      "StringsAttached normalized hand space (translation, scale, rotation per src/cv/normalizer.ts)",
    landmarkCount: 21,
    generatedBy: "scripts/generate-chord-templates.ts (build-time, deterministic)",
    note: "Static canonical templates. NOT generated by Gemini.",
  },
  chords: {
    C: cNorm.landmarks,
    Am: amNorm.landmarks,
  },
};

const outPath = resolve(__dirname, "../src/assets/templates/chords.json");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, JSON.stringify(payload, null, 2) + "\n");
console.log(`Wrote ${outPath}`);
