// Canonical synthetic hand geometry for the ukulele chord templates.
//
// These define the static reference configurations for the C and Am chords,
// expressed as raw 21-landmark hands in the same coordinate system the
// runtime normalizer consumes. The templates are generated from these (via
// scripts/generate-chord-templates.ts) so the JSON always matches the
// normalization code exactly. Templates are NOT generated by Gemini.
//
// Notes on the geometry: each chord curls ONE fretting finger deeply
// "around" the neck (negative z, toward the palm plane) while the other
// fingers stay extended. This mirrors the coarse hand configuration the
// system is designed to match (coarse configuration, not precision
// fingering).

import type { Landmark3D } from "@/types";

export type V3 = { x: number; y: number; z: number };

export function canonicalBase(): V3[] {
  return [
    { x: 0, y: 0, z: 0 }, // 0 wrist
    { x: -0.35, y: 0.25, z: 0 }, // 1 thumb CMC
    { x: -0.45, y: 0.4, z: 0 }, // 2 thumb MCP
    { x: -0.55, y: 0.5, z: 0 }, // 3 thumb IP
    { x: -0.65, y: 0.55, z: 0 }, // 4 thumb tip
    { x: -0.28, y: -0.55, z: 0 }, // 5 index MCP
    { x: -0.3, y: -0.8, z: 0 }, // 6 index PIP
    { x: -0.32, y: -1.0, z: 0 }, // 7 index DIP
    { x: -0.34, y: -1.18, z: 0 }, // 8 index tip
    { x: 0, y: -0.58, z: 0 }, // 9 middle MCP
    { x: 0, y: -0.85, z: 0 }, // 10 middle PIP
    { x: 0, y: -1.06, z: 0 }, // 11 middle DIP
    { x: 0, y: -1.24, z: 0 }, // 12 middle tip
    { x: 0.28, y: -0.55, z: 0 }, // 13 ring MCP
    { x: 0.3, y: -0.8, z: 0 }, // 14 ring PIP
    { x: 0.32, y: -1.0, z: 0 }, // 15 ring DIP
    { x: 0.34, y: -1.18, z: 0 }, // 16 ring tip
    { x: 0.56, y: -0.5, z: 0 }, // 17 pinky MCP
    { x: 0.58, y: -0.72, z: 0 }, // 18 pinky PIP
    { x: 0.6, y: -0.9, z: 0 }, // 19 pinky DIP
    { x: 0.62, y: -1.06, z: 0 }, // 20 pinky tip
  ];
}

/** Curl a finger toward the palm; `z` controls the wrap depth. */
export function curlFinger(
  joints: V3[],
  mcp: number,
  pip: number,
  dip: number,
  tip: number,
  z: number
): V3[] {
  const out = joints.slice();
  out[pip] = { ...joints[pip], y: joints[mcp].y + 0.05, x: joints[mcp].x + 0.04, z: z * 0.4 };
  out[dip] = { ...joints[dip], y: joints[mcp].y + 0.05, x: joints[mcp].x + 0.04, z: z * 0.7 };
  out[tip] = { ...joints[tip], y: joints[mcp].y + 0.05, x: joints[mcp].x + 0.04, z: z };
  return out;
}

/** Wrap the thumb behind the neck (negative z) and pull it inward by `x`. */
export function wrapThumb(joints: V3[], z: number, x: number): V3[] {
  const out = joints.slice();
  out[1] = { ...joints[1], z: z * 0.3, x: joints[1].x + x };
  out[2] = { ...joints[2], z: z * 0.6, x: joints[2].x + x };
  out[3] = { ...joints[3], z: z * 0.85, x: joints[3].x + x };
  out[4] = { ...joints[4], z: z, x: joints[4].x + x };
  return out;
}

const asLandmarks = (joints: V3[]): Landmark3D[] =>
  joints.map((p) => ({ x: p.x, y: p.y, z: p.z, visibility: 1 }));

/**
 * Canonical C chord: ring finger curled around the neck, thumb wrapped behind.
 */
export function buildRawC(): Landmark3D[] {
  const withRing = curlFinger(canonicalBase(), 13, 14, 15, 16, -1.0);
  return asLandmarks(wrapThumb(withRing, -0.9, -0.12));
}

/**
 * Canonical Am chord: middle finger curled around the neck, pinky braced.
 */
export function buildRawAm(): Landmark3D[] {
  const withMiddle = curlFinger(canonicalBase(), 9, 10, 11, 12, -1.0);
  return asLandmarks(curlFinger(withMiddle, 17, 18, 19, 20, -0.8));
}

/** A full fist (all four fingers curled) — a common "bad C" configuration. */
export function buildRawFist(): Landmark3D[] {
  let joints = canonicalBase();
  joints = curlFinger(joints, 5, 6, 7, 8, -1.0);
  joints = curlFinger(joints, 9, 10, 11, 12, -1.0);
  joints = curlFinger(joints, 13, 14, 15, 16, -1.0);
  joints = curlFinger(joints, 17, 18, 19, 20, -1.0);
  return asLandmarks(joints);
}

/** An open, flat hand (all fingers extended, no curl). */
export function buildRawOpen(): Landmark3D[] {
  return asLandmarks(canonicalBase());
}

/**
 * A "release" hand: all four fingers curled forward (positive z), opposite to
 * the chord templates. Used to represent the hand between C and Am.
 */
export function buildRawNeutral(): Landmark3D[] {
  let joints = canonicalBase();
  joints = curlFinger(joints, 5, 6, 7, 8, 1.3);
  joints = curlFinger(joints, 9, 10, 11, 12, 1.3);
  joints = curlFinger(joints, 13, 14, 15, 16, 1.3);
  joints = curlFinger(joints, 17, 18, 19, 20, 1.3);
  return asLandmarks(joints);
}
